function showAffirmation() {
  let affirmations = [
  "I am worthy of everything I desire.",
  "I take small steps every day, and they add up.",
  "Good things are always finding me.",
  "I am open to love, success, and abundance.",
  "Money flows to me in fun and unexpected ways.",
  "I am open to receiving limitless abundance.",
  "My income expands as I grow into my best self.",
  "I attract aligned opportunities that increase my wealth.",
  "I am worthy of financial freedom and ease.",
  "I love the feeling of being supported by money.",
  "My mindset creates wealth effortlessly.",
  "Everything I desire is already on its way to me.",
  "I radiate confidence and positive energy wherever I go.",
  "My heart is open to giving and receiving love.",
  "I trust that the universe always has my back.",
  "I am exactly where I need to be right now.",
  "I attract only good people and good experiences into my life.",
  "I let go of fear and welcome peace.",
  "I am safe, loved, and supported by the universe.",
  "My dreams are becoming my reality.",
  "I am grateful for all the blessings in my life.",
  "I am aligned with the energy of abundance.",
  "The better I feel, the more I attract good things.",
  "I am constantly evolving into my highest self.",
  "Love flows to me easily and effortlessly.",
  "I am a magnet for miracles.",
  "Every challenge helps me grow stronger and wiser.",
  "I am powerful beyond measure.",
  "I trust divine timing and surrender control.",
  "I am creating a beautiful life filled with joy.",
  "The universe is conspiring in my favor.",
  "I am thankful for the abundance that surrounds me.",
  "I attract opportunities that align with my purpose.",
  "I am enough just as I am.",
  "My energy is magnetic and uplifting.",
  "I deserve happiness, peace, and prosperity.",
  "I let go of everything that no longer serves me.",
  "I choose to see love and goodness in every situation.",
  "I am free from doubt and fear.",
  "I believe in myself and my dreams.",
  "I am calm, centered, and grounded.",
  "Money loves to find its way to me.",
  "My creativity flows effortlessly.",
  "I am glowing with positive energy.",
  "I am attracting success in all areas of my life.",
  "The universe is guiding me to my highest potential.",
  "I am surrounded by loving energy.",
  "I am grateful for where I am and excited for where I’m going.",
  "I allow joy and love to fill my heart every day.",
  "I am open to miracles beyond my imagination.",
  "I am unstoppable when I am aligned with my purpose.",
  "My life is full of abundance.",
  "Everything always works out for me.",
  "I am a beautiful expression of light and love.",
  "I am worthy of deep, healthy, and soulful love.",
  "I forgive myself and move forward with ease.",
  "I attract people who uplift and inspire me.",
  "My thoughts create my reality, and I choose positivity.",
  "I am proud of how far I’ve come and excited for what’s next.",
  "I am confident in my ability to manifest my desires.",
  "The energy I put out always comes back multiplied.",
  "I am grateful for today and open to endless possibilities.",
  "I am living my dream life, one aligned step at a time.",
  "The universe delights in giving me surprises and blessings.",
  "I am divinely guided every moment of the day.",
  "My intuition always leads me in the right direction.",
  "I am love, I am light, I am enough.",
  "I choose faith over fear.",
  "I celebrate my progress, no matter how small.",
  "I release resistance and allow abundance to flow.",
  "I am a miracle in motion.",
  "I am surrounded by beauty, peace, and grace.",
  "I radiate joy and attract joyful experiences.",
  "Everything I need is already within me.",
  "I deserve all the amazing things coming my way.",
  "I trust myself and the path I’m walking.",
  "My vibration attracts miracles daily.",
  "I am constantly attracting abundance, love, and joy.",
  "The universe supports my bold dreams.",
  "I am becoming the person I was meant to be.",
  "I am grateful for the magic unfolding in my life."
  ];

let random = Math.floor(Math.random() * affirmations.length);
  let out = document.getElementById("affirmOut");
  out.textContent = affirmations[random];
}